name: Run benchamrks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_etcd_benchmarks:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
