name: Run benchamrks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_etcd_benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository branch
        uses: actions/checkout@v3

      - name: Start up etcd
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Peek CPU cores & Memory size
        run: |
          free -mh
          lscpu | grep 'CPU(s):'

      - name: download go-ycsb
        run: |
          cd bin
          wget -c https://github.com/pingcap/go-ycsb/releases/latest/download/go-ycsb-linux-amd64.tar.gz -O - | tar -xz
          cd ..

      - name: Load test data
        run: |
          bin/go-ycsb load etcd -P workloads/etcd_offcial_workload

      - name: Peek etcd keys
        run: |
          docker exec ycsb-etcd etcdctl get --prefix ""
          # base64 encode data
          docker exec ycsb-etcd etcdctl --write-out="json" get --prefix ""
          # docker exec ycsb-etcd etcdctl snapshot save my.db
          # docker exec ycsb-etcd etcdutl --write-out=table snapshot status my.db
          docker exec ycsb-etcd etcdctl endpoint status --write-out="table"


      - name: Running test
        run: |
          bin/go-ycsb run etcd -P workloads/etcd_offcial_workload
