name: Run benchamrks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_etcd_benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository main branch
        uses: actions/checkout@v3

      - name: Checkout Repository main branch
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: load test data
        run: |
          ./bin/go-ycsb load etcd -P workloads/etcd_offcial_workload

      - name: running test
        run: |
          ./bin/go-ycsb run etcd -P workloads/etcd_offcial_workload
