name: Run benchamrks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_etcd_benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository branch
        uses: actions/checkout@v3

      - name: Start up etcd
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: download go-ycsb
        run: |
          cd bin
          wget -c https://github.com/pingcap/go-ycsb/releases/latest/download/go-ycsb-linux-amd64.tar.gz -O - | tar -xz
          cd ..

      - name: Load test data
        run: |
          bin/go-ycsb load etcd -P workloads/etcd_offcial_workload

      - name: Running test
        run: |
          bin/go-ycsb run etcd -P workloads/etcd_offcial_workload
